apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kslack.fullname" . }}-config
  labels:
    {{- include "kslack.labels" . | nindent 4 }}
data:
  permissions.yaml: |
    {{- toYaml .Values.permissions | nindent 4 }}
