apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kslack.fullname" . }}-secrets
  labels:
    {{- include "kslack.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-bot-token: {{ required "secrets.slackBotToken is required" .Values.secrets.slackBotToken | quote }}
  slack-app-token: {{ required "secrets.slackAppToken is required" .Values.secrets.slackAppToken | quote }}
  slack-signing-secret: {{ required "secrets.slackSigningSecret is required" .Values.secrets.slackSigningSecret | quote }}
